name = "Seraph"
uuid = "96af2be4-7615-4b4e-8545-65312eddaa3e"
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"

[compat]
Colors = "0.13.1"
