name = "Sokaris"
uuid = "96af2be4-7615-4b4e-8545-65312eddaa3e"
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Colors = "0.13.1"
ImageFiltering = "0.7.12"
ImageTransformations = "0.10.2"
Images = "0.26.2"
Random = "1.11.0"
